# Generated by Django 4.2.7 on 2025-10-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_employee",
            field=models.BooleanField(default=True),
        ),
    ]
