# Generated by Django 4.2.7 on 2025-10-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_user_is_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="departament",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
