# Generated by Django 4.2.7 on 2025-10-01 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_user_departament"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="departament",
            new_name="department",
        ),
    ]
